### ISSUE TITLE
HTTPS Cert

### ISSUE THREAD

**Issue by chsedotsh** [FlipEnergy/personal-website#1]
Saw your post on reddit, and noticed you didn't have an HTTPS cert, didn't know if that was intentional but I'd highly recommend you grab one.

```
sudo apt-get update
sudo apt-get install software-properties-common
sudo add-apt-repository universe
sudo add-apt-repository ppa:certbot/certbot
sudo apt-get update
sudo apt-get install certbot python3-certbot-nginx
sudo certbot --nginx
```

Then setup a cronjob to renew certs
`
sudo crontab -e
`
(Then choose whatever editor you want then paste this below all the comments):

```
0 0 * * * sudo certbot renew
# Every day at midnight, renew any certs.
```

(Obviously you'd need to port forward 443 and add to your docker compose.)

Also, I noticed your resume was a link to a google drive document that's in the trash, so it won't actually pull up anything.

[Edit: Just realized your web server is running off of docker, try the LE Docker](https://hub.docker.com/r/linuxserver/letsencrypt)

**Comment by FlipEnergy** [comment]
Thanks for the interest. I'm mostly lazy. My crappy site is literally a static page with nothing auth related so I haven't bothered. Getting a cert for it is in the backlog.

**Comment by FlipEnergy** [comment]
Oh the Google drive link is dead since I cleared it. I'll fix that. Thanks

**Comment by chsedotsh** [comment]
[There's still plenty of reasons a static site should use HTTPS](https://www.troyhunt.com/heres-why-your-static-website-needs-https/)

But yeah, makes sense. :D

**Comment by FlipEnergy** [comment]
Done.

pleasenoddos.com

https://github.com/FlipEnergy/ansible-playground/blob/master/roles/site_node/tasks/lets_encrypt.yml
